import os
import re
from datetime import datetime
from app.models.paper import Paper

def sanitize_filename(name: str) -> str:
    # Remove invalid chars for Windows/Linux files
    return re.sub(r'[\\/*?:"<>|]', "", name).strip()

def export_paper_to_markdown(paper: Paper, export_dir: str) -> str:
    """
    Generates an Obsidian-compatible Markdown file for the paper.
    Returns the absolute path of the created file.
    """
    if not os.path.exists(export_dir):
        os.makedirs(export_dir, exist_ok=True)
    
    # Format filename: "Year - Title.md" or just "Title.md"
    clean_title = sanitize_filename(paper.title)
    filename = f"{clean_title}.md"
    filepath = os.path.join(export_dir, filename)
    
    # Process Tags (ensure they are strings)
    # Note: paper.tags isn't in SQLModel explicitly as List yet, assumed handled or string.
    # In V2.1 models we didn't add tags column explicitly as List[str], usually needs JSON column.
    # For now, let's assume it might not exist or is a string.
    # I'll check paper model again in a sec, but let's be safe.
    
    # Construct Content
    content = f"""---
title: "{clean_title}"
author: "{paper.author}"
year: {paper.year}
tags: [phantom-lib, paper]
created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
status: inbox
---

# {paper.title}

## 📄 Abstract
> {paper.abstract or "No abstract extracted."}

## 🧠 Mind Hack Analysis
### 🌑 Shadow (The Problem)
{paper.shadow_problem or "Not analyzed yet."}

### 🎭 Persona (The Solution)
{paper.persona_solution or "Not analyzed yet."}

### 💔 Weakness (Critical Flaw)
{paper.weakness_flaw or "Not analyzed yet."}

---
## 📝 Notes
- 

---
*Generated by Phantom Library 🎩*
"""
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
        
    return filepath
