"""Initial_migration_with_file_path

Revision ID: 3ba94a8ee8c7
Revises: 
Create Date: 2026-01-27 14:26:55.086414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ba94a8ee8c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('paper', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'created_at')
    op.drop_column('paper', 'file_path')
    # ### end Alembic commands ###
