"""Add_user_notes_to_paper

Revision ID: 9abcc058887f
Revises: 3ba94a8ee8c7
Create Date: 2026-01-27 16:01:41.049632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9abcc058887f'
down_revision: Union[str, Sequence[str], None] = '3ba94a8ee8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('user_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'user_notes')
    # ### end Alembic commands ###
